language: python
dist: trusty
sudo: required
python:
  - "2.7"
  - "3.4"
before_install:
  - sudo echo "deb http://archive.panda3d.org/ubuntu trusty-dev main" >> /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install -y panda3d1.10
script: setup.py --auto-install
