

# This file stores internal settings of the pipeline. It does not contain the
# plugin settings, but just the basic settings of the internal pipeline components.

settings:

    # This are the settings affecting the lighting part of the pipeline,
    # including builtin shadows and lights. 
    lighting:


        # The pipeline uses clustered deferred shading, this means that the
        # screen gets divided into tiles, and for each tile, the lights affecting
        # that tile are accumulated. You can adjust the tile size here (in pixels),
        # optimal is a tile size which is not too big (to avoid unecessary shading),
        # but also not too small (to avoid excessive culling).
        culling_grid_size_x: 32
        culling_grid_size_y: 16

        # The view frustum is additionally divived into slices, to be able to do
        # better culling. If you use a higher amount of slices, the culling will
        # get more exact, but also more expensive. You have to find the optimal
        # size depending on your scene.
        culling_grid_slices: 32

        # This controls the maximum culling distance in world space. After this
        # distance, no lights are rendered anymore. If you choose a lower 
        # distance, this *can* positively impact performance, but you should not
        # set it too low, to avoid getting artifacts.
        culling_max_distance: 140.0


        # Controls the size of a slice in culling. Lower values might produce
        # better performance for less amount of lights, but higher values should
        # be used when using many lights, e.g. > 1024, to get better coherency.
        culling_slice_width: 256
