
# Render Pipeline Plugin Configuration
# Instead of editing this file, prefer to use the Plugin Configurator
# Any formatting and comments will be lost

enabled:
    # - sslr
    # - clouds
    - pssm
    - color_correction
    - scattering
    - ao
    - smaa
    - env_probes
    # - vxgi
    - fxaa
    - bloom
    - motion_blur


overrides:
    ao:
        blur_normal_factor: 1.53
        blur_depth_factor: 1.2
        occlusion_strength: 1.54
        technique: SSAO
        ssao_sample_radius: 136.66999
        ssao_sample_count: 5
        ssao_bias: 0.0
        ssao_max_distance: 7.11
        hbao_sample_radius: 100.0
        hbao_ray_count: 8
        hbao_ray_steps: 3
        hbao_tangent_bias: 0.6889
        hbao_max_distance: 8.23
        ssvo_sample_count: 4
        ssvo_sphere_radius: 11.34556
        ssvo_max_distance: 1.49
        alchemy_sample_radius: 62.06
        alchemy_num_samples: 8
        alchemy_max_distance: 4.08
        ue4ao_sample_radius: 100.0
        ue4ao_sample_count: 8
        ue4ao_max_distance: 4.3

    bloom:
        num_mipmaps: 8
        bloom_strength: 0.7
        remove_fireflies: True
        lens_dirt_factor: 0.8111

    clouds:
        cloud_decay: 5.78
        raymarch_steps: 64

    color_correction:
        tonemap_operator: uncharted2
        reinhard_version: rgb
        exponential_factor: 1.05
        uc2t_shoulder_strength: 0.22
        uc2t_linear_strength: 0.3
        uc2t_linear_angle: 0.1
        uc2t_toe_strength: 0.2
        uc2t_toe_numerator: 0.01
        uc2t_toe_denumerator: 0.3
        uc2t_reference_white: 11.2
        vignette_strength: 0.0889
        film_grain_strength: 0.12
        color_lut: color_lut.png
        use_chromatic_aberration: True
        chromatic_aberration_strength: 0.0311
        chromatic_aberration_samples: 2
        manual_camera_parameters: False
        min_exposure_value: 0.0
        max_exposure_value: 1.0
        exposure_bias: 0.0
        brightness_adaption_rate: 2.67
        darkness_adaption_rate: 0.79
        use_sharpen: True
        sharpen_strength: 0.6667
        sharpen_twice: False

    env_probes:
        probe_resolution: 128
        diffuse_probe_resolution: 4
        max_probes: 16
        max_probes_per_cell: 5

    fxaa:
        quality: ultra
        subpixel_quality: 0.5
        edge_threshold: 0.075
        min_threshold: 0.7114

    motion_blur:
        tile_size: 32
        blur_factor: 0.5
        max_blur_radius: 10.0
        num_samples: 12

    pssm:
        max_distance: 100.0
        logarithmic_factor: 0.8
        sun_distance: 2520.0
        split_count: 5
        resolution: 1024
        border_bias: 0.1167
        use_pcf: True
        filter_sample_count: 18
        filter_radius: 2.52
        fixed_bias: 0.0
        slope_bias: 2.27999
        normal_bias: 0.28
        use_pcss: False
        pcss_search_samples: 32
        pcss_penumbra_size: 300.0
        vsm_resolution: 4096
        scene_shadow_resolution: 1024

    scattering:
        scattering_method: eric_bruneton
        ground_reflectance: 0.1
        rayleigh_height_scale: 8.0
        mie_height_scale: 1.45
        mie_phase_factor: 0.21
        beta_mie_scattering: 4.0
        enable_godrays: False

    smaa:
        use_reprojection: True
        smaa_quality: ultra

    sslr:

    vxgi:
        grid_resolution: 256
        grid_ws_size: 140.0
        diffuse_cone_steps: 13
        specular_cone_steps: 150

