
# Render Pipeline Plugin Configuration
# Instead of editing this file, prefer to use the Plugin Configurator
# Any formatting and comments will be lost

enabled:
    - sslr
    # - clouds
    - pssm
    - color_correction
    - scattering
    # - dof
    - ao
    # - skin_shading
    - smaa
    - env_probes
    # - vxgi
    # - fxaa
    - bloom
    - motion_blur


overrides:
    ao:
        blur_normal_factor: 4.94
        blur_depth_factor: 4.83
        occlusion_strength: 1.21
        technique: SSAO
        ssao_sample_radius: 79.61
        ssao_sample_count: 8
        ssao_bias: 0.0333
        ssao_max_distance: 6.89
        hbao_sample_radius: 119.11
        hbao_ray_count: 4
        hbao_ray_steps: 3
        hbao_tangent_bias: 0.5889
        hbao_max_distance: 4.9
        ssvo_sample_count: 4
        ssvo_sphere_radius: 7.86
        ssvo_max_distance: 0.6
        alchemy_sample_radius: 127.8901
        alchemy_num_samples: 8
        alchemy_max_distance: 6.07
        ue4ao_sample_radius: 110.33
        ue4ao_sample_count: 8
        ue4ao_max_distance: 1.87

    bloom:
        num_mipmaps: 8
        bloom_strength: 0.45
        remove_fireflies: False
        lens_dirt_factor: 0.7111

    clouds:
        cloud_decay: 5.78
        raymarch_steps: 64

    color_correction:
        tonemap_operator: exponential
        reinhard_version: rgb
        exponential_factor: 1.4
        uc2t_shoulder_strength: 0.22
        uc2t_linear_strength: 0.3
        uc2t_linear_angle: 0.1
        uc2t_toe_strength: 0.2
        uc2t_toe_numerator: 0.01
        uc2t_toe_denumerator: 0.3
        uc2t_reference_white: 11.2
        vignette_strength: 0.2667
        film_grain_strength: 0.0
        color_lut: color_lut.png
        use_chromatic_aberration: True
        chromatic_aberration_strength: 0.1196
        chromatic_aberration_samples: 1
        manual_camera_parameters: False
        min_exposure_value: 0.012
        max_exposure_value: 1.0
        exposure_bias: 0.0
        brightness_adaption_rate: 2.67
        darkness_adaption_rate: 0.79
        use_sharpen: True
        sharpen_strength: 0.22
        sharpen_twice: False

    dof:
        some_int_setting: 5
        some_float_setting: 2.5
        some_enum: value2
        some_bool: False

    env_probes:
        probe_resolution: 128
        diffuse_probe_resolution: 4
        max_probes: 16
        max_probes_per_cell: 5

    fxaa:
        quality: ultra
        subpixel_quality: 0.5
        edge_threshold: 0.075
        min_threshold: 0.7114

    motion_blur:
        num_camera_samples: 6
        camera_blur_factor: 0.24444
        blur_factor: 0.5
        tile_size: 32
        max_blur_radius: 10.0
        num_samples: 12

    pssm:
        max_distance: 45.0
        logarithmic_factor: 2.67
        sun_distance: 1145.0
        split_count: 3
        resolution: 2048
        border_bias: 0.01943
        use_pcf: True
        filter_sample_count: 32
        filter_radius: 9.89
        fixed_bias: 0.0889
        slope_bias: 0.39
        normal_bias: 0.0
        use_pcss: False
        pcss_search_samples: 32
        pcss_penumbra_size: 300.0
        use_distant_shadows: True
        dist_shadow_resolution: 1024
        dist_shadow_clipsize: 250.0
        scene_shadow_resolution: 1024

    scattering:
        scattering_method: eric_bruneton
        ground_reflectance: 0.1
        rayleigh_height_scale: 8.0
        mie_height_scale: 1.45
        mie_phase_factor: 0.21
        beta_mie_scattering: 4.0
        enable_godrays: False

    skin_shading:
        quality: high
        blur_scale: 1.0

    smaa:
        use_reprojection: True
        smaa_quality: ultra

    sslr:

    vxgi:
        grid_resolution: 256
        grid_ws_size: 140.0
        diffuse_cone_steps: 13
        specular_cone_steps: 150

