
# Render Pipeline Plugin Configuration
# Instead of editing this file, prefer to use the Plugin Configurator
# Any formatting and comments will be lost

enabled:
    - ao
    - bloom
    - color_correction
    - env_probes
    - motion_blur
    - pssm
    - scattering
    - skin_shading
    - smaa
    - ssr
    # - clouds
    # - dof
    # - fxaa
    # - volumetrics
    # - vxgi


overrides:
    ao:
        blur_normal_factor: 6.92
        blur_depth_factor: 2.19
        occlusion_strength: 1.6
        clip_length: 12
        technique: SSAO
        ssao_sample_radius: 79.61
        ssao_sample_count: 5
        ssao_bias: 0.0333
        ssao_max_distance: 6.89
        hbao_sample_radius: 255.17
        hbao_ray_count: 4
        hbao_ray_steps: 3
        hbao_tangent_bias: 0.6556
        hbao_max_distance: 11.56
        ssvo_sample_count: 4
        ssvo_sphere_radius: 17.94
        ssvo_max_distance: 0.82
        alchemy_sample_radius: 211.28
        alchemy_num_samples: 4
        alchemy_max_distance: 4.74
        ue4ao_sample_radius: 110.33
        ue4ao_sample_count: 4
        ue4ao_max_distance: 1.87

    bloom:
        num_mipmaps: 8
        bloom_strength: 0.23
        remove_fireflies: False
        lens_dirt_factor: 0.0

    clouds:
        raymarch_steps: 160

    color_correction:
        tonemap_operator: reinhard
        reinhard_version: rgb
        exponential_factor: 1.51
        uc2t_shoulder_strength: 0.22
        uc2t_linear_strength: 0.3
        uc2t_linear_angle: 0.1
        uc2t_toe_strength: 0.2
        uc2t_toe_numerator: 0.01
        uc2t_toe_denumerator: 0.3
        uc2t_reference_white: 11.2
        vignette_strength: 0.73343
        film_grain_strength: 0.1333
        color_lut: film_luts/kodak_gold_200.png
        use_chromatic_aberration: True
        chromatic_aberration_strength: 0.2745
        chromatic_aberration_samples: 2
        manual_camera_parameters: False
        min_exposure_value: 0.0
        max_exposure_value: 1.0
        exposure_scale: 2.78
        brightness_adaption_rate: 3.67
        darkness_adaption_rate: 0.73
        use_sharpen: True
        sharpen_strength: 1.06
        sharpen_twice: False

    dof:
        focal_point: 5.0
        focal_size: 6.67
        blur_strength: 0.0
        near_blur_strength: 0.0

    env_probes:
        probe_resolution: 128
        diffuse_probe_resolution: 2
        max_probes: 16
        max_probes_per_cell: 3

    fxaa:
        quality: ultra
        subpixel_quality: 0.5111
        edge_threshold: 0.156
        min_threshold: 0.7114

    motion_blur:
        num_camera_samples: 6
        camera_blur_factor: 0.4
        blur_factor: 0.5
        tile_size: 32
        max_blur_radius: 10.0
        num_samples: 12

    pssm:
        max_distance: 91.0
        logarithmic_factor: 2.37
        sun_distance: 100.0
        split_count: 5
        resolution: 1536
        border_bias: 0.0583
        use_pcf: True
        filter_sample_count: 8
        filter_radius: 0.54
        fixed_bias: 0.4889
        slope_bias: 0.11
        normal_bias: 0.39
        use_pcss: False
        pcss_search_samples: 8
        pcss_penumbra_size: 11.0
        use_distant_shadows: True
        dist_shadow_resolution: 1024
        dist_shadow_clipsize: 12924.44444
        dist_shadow_sundist: 9386.67
        scene_shadow_resolution: 512
        scene_shadow_sundist: 100.0

    scattering:
        scattering_method: eric_bruneton
        ground_reflectance: 0.1
        rayleigh_factor: 0.5
        rayleigh_height_scale: 8.0
        mie_height_scale: 1.45
        mie_phase_factor: 0.21
        beta_mie_scattering: 4.0
        enable_godrays: False

    skin_shading:
        quality: medium
        blur_scale: 0.43

    smaa:
        use_reprojection: True
        smaa_quality: ultra
        jitter_pattern: halton16
        history_length: 16
        jitter_amount: 1.0

    ssr:
        effect_scale: 1.0
        trace_steps: 64
        history_length: 16
        abort_on_object_infront: True
        intial_bias: 0.1
        hit_tolerance: 0.1
        roughness_fade: 1.0
        skip_invalid_samples: False
        border_fade: 0.005

    volumetrics:
        enable_volumetric_shadows: True
        volumetric_shadow_intensity: 1.0

    vxgi:
        grid_resolution: 256
        grid_ws_size: 100.0
        diffuse_cone_steps: 32
        specular_cone_steps: 150

