
# This file controls the order of all render stages.
# Usually you do not have to modify this, except if you are adding new plugins.
# If you move stages, you should know what you do.
# Commenting out a stage won't disable it, but instead produce an error when
# it is created.

global_stage_order:

  # Shadows, Environment and Voxelization
  - PSSMShadowStage
  - PSSMDistShadowStage
  - PSSMSceneShadowStage
  - VoxelizationStage
  - ScatteringEnvmapStage
  - EnvironmentCaptureStage

  # Main scene
  - GBufferStage
  - ShadowStage
  - DownscaleZStage

  # Light(-culling)
  - FlagUsedCellsStage
  - CollectUsedCellsStage
  - CullLightsStage
  - CullProbesStage

 # Plugins
  - CloudVoxelStage
  - AOStage
  - ApplyLightsStage
  - PSSMStage
  - ScatteringStage
  - ApplyCubemapsStage
  - VXGIStage
  - AmbientStage
  - SSLRStage
  - ApplyCloudsStage
  - AutoExposureStage
  - BloomStage

  # Post AA & Effects
  - TonemappingStage
  - SMAAStage
  - FXAAStage
  - SharpenStage
  - ColorCorrectionStage

  # Finishing stages, do not insert anything below
  - FinalStage
  - UpdatePreviousPipesStage
