
# Default effect file, used for all objects if not overridden

Vertex:
    template: default

Fragment.GBuffer:
    template: default

Fragment.Shadows:
    template: default

Fragment.Voxelize:
    template: default
